### PR TITLE
Packaging and PyPI distribution

### LINKED ISSUE #44: Create PyPi package
It would be very nice if it was possible to simplify the installation of PaperTTY to just `pip install papertty`. Any help with achieving this is appreciated.

### PR DESCRIPTION
**Pull request by colin-nolan**
This PR sets up packaging with a [`pyproject.toml` file](https://www.python.org/dev/peps/pep-0518/) and the help of [Poetry](https://python-poetry.org/).

I have tried to change as little as possible to get this to work. However, it was necessary to create a `papertty` package (directory) and move `papertty.py` + the drivers into that because I don't think it's possible to have a single module in addition to a package (which in this case was the `drivers` package). 

I've setup [`papertty` on PyPI](https://pypi.org/project/papertty/), which I will pass control over to you if you let me know your PyPI details. Installation for users would be as simple as:
```
pip install papertty
```
I've then made the program available through the `papertty` command:
```
papertty --help
```

Installation from source is possible without any special tools using:
```
# Requires a modern version of pip (at least >18 - I've confirmed with 20)
pip install .
```
However, as a developer, I've found Poetry is useful, particularly when uploading to PyPI.

I've tried to align the README.md with the change but it was a little difficult (the need for a cleanup is mentioned in https://github.com/joukos/PaperTTY/issues/43).

Closes #44.

### CODE REVIEW

**Comment by joukos** [comment]
Nice, this is a very welcome change, thanks! I'll need to take a look at the code a bit and try it out. I also yesterday considered rewriting the README, hopefully soonish - now that installation is simple, usage ought to be too.

**Comment by joukos** [comment]
Update about this - I've been very busy as usual so this lagged quite a bit, sorry about that. I've rewritten (ie. condensed a lot) most of the README in preparation for putting this to PyPI, although it's not quite done yet. Perhaps we should get this stuff sorted somehow first, since it would be very useful even without the documentation fixes. I'm not too familiar with Poetry, but I don't immediately see it hurting the project either, so it's probably fine to use it.

I have an account at PyPI with the same username `joukos`, but haven't looked up how Poetry helps with all of this, so a couple of pointers may be needed :) Anyway there's a few conflicts to fix first since things have changed - I think I might also merge a new driver PR that's pending, so maybe this can be sorted after that, or when you feel like it.

Thanks again for your work on this, it's very appreciated.

**Comment by colin-nolan** [comment]
@joukos I have added you as a maintainer of the package on PyPI (I will upgrade this to owner once you confirm that I have added the correct account!).

A nice overview of Poetry [can be found here](https://johnfraney.ca/posts/2019/05/28/create-publish-python-package-poetry/). I'm happy to help with any specific problems though. I've found Poetry provides a developer friendly way of building and publishing Python packages, in addition to being much better WRT dependency management. To publish, it's as simple as bumping the version number, then:
```
poetry build
poetry publish
```
(Probably best to play with the PyPi test package index before going to prod!).

I've rebased against master. I believe I also got the new colour driver into that update.

**Comment by joukos** [comment]
> @joukos I have added you as a maintainer of the package on PyPI (I will upgrade this to owner once you confirm that I have added the correct account!).

Thanks, I see the project in my account now, so it's the correct one :)

**Comment by joukos** [comment]
I went and merged this now - will add some minor tweaks soon.

**Comment by joukos** [comment]
Phew. Thanks a lot! I added a temporary quick help to the README and moved fonts etc. to `resources` subdirectory. Now should just finish the docs rewrite at some point, but at least it should be pippable now which is great.

**Pull request merged**
